#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: /log/
#  file: /weixinsell.log
#  level:
#    com.kaven.weixinsell.LoggerTest: debug

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root2
    password: "015036"
    url: jdbc:mysql://47.112.7.219:3306/sell?characterEncoding=UTF8&useSSL=false
  jpa:
    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell